FROM node:14-alpine

# 设置环境变量
ENV NODE_ENV=development

# 设置工作目录
WORKDIR /code

# 将当前目录下的所有文件复制到容器内的 /code 目录
COPY . .

# 设置 npm 配置并安装依赖
RUN npm config set sass_binary_site=https://npm.taobao.org/mirrors/node-sass && \
    npm install --registry=https://registry.npmjs.org/

# 暴露端口（根据您的应用程序端口调整）
EXPOSE 3000

# 设置容器启动时执行的命令
ENTRYPOINT ["npm", "run", "dev:docker"]


